library(tidyverse)
library(rvest)
library(stringr)
webpage <- read_html("https://www.metacritic.com/browse/albums/score/metascore/all?sort=desc")
alldata <- html_nodes(webpage, '.product_wrap')
data.text <- html_text(alldata)
data.text %>% head(3)
metascore <- html_nodes(webpage, '.positive')
meta_text <- html_text(metascore)
meta_text %>% head(3)
userscore <- html_nodes(webpage, '.textscore')
user_text <- html_text(userscore)
user_text %>% head(3)
album <- html_nodes(webpage, '.first_product a')
album_text <- html_text(album)
album_text %>% head(3)
x <- head(meta_text, -5)
Top100 <- gsub("[\r\n\t]", "", data.text)
releasedate <- html_nodes(webpage, '.full_release_date .data')
releasedate %>% head(3)
release.date <- releasedate %>% html_text()
release.dates <- as.Date(release.date,format='%B %d, %Y')
x2 <- as.numeric(user_text)
UserScores <- x2*10
CriticScores <- as.numeric(x)
scores <- data.frame(UserScores,CriticScores)
scores2 <- data.frame(UserScores,CriticScores,release.dates)
scores2 %>% head(5)
plot <- ggplot(data = scores, mapping = aes(x = user_text, y = x))
plot + geom_point(colour = "red")
plot2 <- ggplot(scores2, aes(release.dates, y=value, color=varibale)) + geom_point(aes(y=CriticScores, col="CriticScores")) + geom_point(aes(y=UserScores, col="UserScores"))
plot3 <- ggplot(scores2, aes(x=release.dates)) + geom_density(color = "darkblue", fill = "lightblue")
