library(readr)
wages <- read_csv("~/DScourseS19/ModelingOptimization/wages.csv")
View(wages)
completeFun <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}
Wages.2 <- completeFun(wages,c("hgc","tenure"))
library(stargazer)
stargazer(as.data.frame(Wages.2))
Wages.3 <- na.omit(Wages.2)
lm1 <- lm(logwage ~ ., Wages.3)
Wages.2$logwage[is.na(Wages.2$logwage)] = mean(Wages.2$logwage, na.rm = TRUE)
lm2 <- lm(logwage ~ .,Wages.2)
summary(lm1)
summary(lm2)
library(mice)
Wages.4 <- mice(Wages.2,m=5,maxit=50,meth='pmm',seed=500)
Wages.5 <- complete(Wages.4,5)
lm3 <- lm(logwage ~.,Wages.5)
summary(lm1)
summary(lm2)
summary(lm3)
stargazer(lm1,lm2,lm3)
